TypedDevs/bashunit

- bashunit
- src/assert.sh
- src/colors.sh
- tests/unit/assert_test.sh
Example:
If it's okay I would also remove the emojis, since they don't have good support on all operating systems/fonts.
Personally, the terminals have many formatting options; take a look at how [Jest.js](https://jestjs.io) uses them.
>  Add colors to passed and failed messages

- src/assert.sh
- tests/unit/assert_test.sh
I've added the `assertNotContains` funtion to the framwork, not using the `assertContains` to don't make any test fail for dependency between functions
> chore: created assertNotContains not using the other assertion

- CHANGELOG.md
- src/test_runner.sh
Issue: https://github.com/Chemaclass/bashunit/issues/9
Add the possibility to filter the test(s) to run by function name/pattern.
> Add option --filter by test name

- Makefile
- bashunit
- src/assert.sh
- src/console_results.sh
- src/test_runner.sh
- tests/unit/assert_test.sh
Related to: https://github.com/Chemaclass/bashunit/issues/23
Allow asserting by using regular expressions:
```bash
assertMatches ".*Pinux*" "GNU/Linux"
```
> chore: added assert matches, refactor global variables to start with underscored and add watch to the Makefile

- src/console_results.sh
- src/test_runner.sh
- tests/unit/render_test.sh
> chore: add execution time to the render results of the test

- Makefile
Related to: https://github.com/Chemaclass/bashunit/issues/20
Source of the static tool: https://github.com/koalaman/shellcheck#from-your-terminal
> chore: add shellcheck

- CHANGELOG.md
- bashunit
- src/assert.sh
- src/console_results.sh
- tests/unit/assert_test.sh
- tests/unit/render_test.sh
MacOS `date` bash function does not support nanoseconds, therefore the feature that to calculate the time taken to run the tests is not possible to implement 😢
> Remove Time taken feature from non-Linux

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/editor_config_lint.yml
- .github/workflows/tests.yml
- Makefile
- bashunit
- src/default_env_config.sh
- src/env_configuration.sh
Prevent that if the project does not have an .env the framework and the make file continue to function normally with the default configuration
- Load only the `.env` if it exists in bashunit as well as in the Makefile
- Add a file with the default config if the `.env` file does not exist or it is not configured
- Change the pipelines so they do not copy the `.env.example` to the `.env` file
- Added color to the linting output
- Make the lint part of the `pre_commit/run` command from the `Makefile`
- Update documentation on the `CONTRIBUITING.md` file
- Update the `github/PULL_REQUEST_TEMPLATE.md` file
- Create a GitHub action to run against our `.editorconfig` to lint formatting issues
> Prevent framework to be broken if there is not a .env file

- docs/README.md
Create a `README.md` to display all assert functions when you go to the `docs/` folder
> Add README.md inside docs/

- .github/CONTRIBUTING.md
- CHANGELOG.md
- Makefile
Fix watch to run on file change and allow to scroll on changes the fix should work on all the OS
- use dependency `fswatch`
- watch all file system and run bashunit in case there is a change, not running the make command because does not work on Windows
> fix: watch on test

- CHANGELOG.md
- Makefile
- src/assert.sh
- tests/unit/assert_test.sh
Implemented 3 assertions more related to the exit code on the bash standards
https://www.cyberciti.biz/faq/bash-get-exit-code-of-command/
- implemented `assertSuccessfulCode`
- implemented `assertGeneralError`
- implemented `assertCommandNotFound`
> fixing test, creating assertSuccessfulCode assertGeneralError assertCommandNotFound

- CHANGELOG.md
- src/assert.sh
- src/test_runner.sh
- tests/unit/console_results_test.sh
Issue: https://github.com/TypedDevs/bashunit/issues/62
Instead of considering the last exit code from the function in order to validate if the test was successful or not, we will check the total of failed assertions before and after running a test.
> Fix error on count assertions

- src/helpers.sh
- src/test_runner.sh
- tests/unit/helpers_test.sh
Issue: https://github.com/Chemaclass/bashunit/issues/56
If you have to test with the same name, we should throw an error or say something, because it could be a bad situation
- Refactor extract function `getFunctionsToRun()`
- assertGeneralError when duplicate functions
> Throw error on duplicated tests

- src/assert.sh
- tests/functional/logic_test.sh
- tests/unit/assert_test.sh
- tests/unit/helpers_test.sh
As a result of the fix #66, no part of our code requires assertions to return any kind of status code, so, for simplification, they have been removed.
Assertions from tests checking that the status code was as expected have also been removed. Instead, assertions should be written in the future to ensure that the corresponding counter (passed/failed) is incremented correctly. However, since this is likely to undergo a refactor to address issue #39, I've decided to postpone it.
- Remove return codes on assertions
> Remove asserts returns

- .github/CONTRIBUTING.md
Add documentation for CONTRIBUTING.md. 
I'm also thinking about adding this documentation in a specific page inside the documentation itself, and in the CONTRIBUTING.md only add a reference to that page, what do you think 🤔
Closes #83
- Add docs
> Add docs setup  in CONTRIBUTING.md

- CHANGELOG.md
- src/helpers.sh
- src/runner.sh
- tests/unit/helpers_test.sh
- tests/unit/setup_teardown_test.sh
You can create functions with the following names in your test script to perform actions before and after test/script:
`setUp`
If this function exists in the test script it will be executed before each test execution.
`setUpBeforeScript`
If this function exists in the test script it will be executed only one time before all tests execution.
`tearDown`
If this function exists in the test script it will be executed after each test execution.
`tearDownAfterScript`
If this function exists in the test script it will be executed only one time after all tests execution.
> add setUp, setUpBeforeScript, tearDown and tearDownAfterScript functions execution

- src/assert.sh
- src/helpers.sh
- src/runner.sh
- tests/unit/helpers_test.sh
Discovered after merging https://github.com/TypedDevs/bashunit/pull/92 CC: @cmayo
- Unset the setup/tearDown functions after each test/script
> TODO: Missing tests for `cleanSetUpAndTearDownAfterScript()` and `cleanSetUpAndTearDownAfterTest()` in a follow up. Anybody can pick this up! ;)
> Unset setup functions

- src/runner.sh
- Avoid using globals from `Runner::loadTestFiles`, instead use local arguments.
> Refactor loadTestFiles to receive args instead of using globals

- docs/.vitepress/theme/style.css
Make boxes slightly less dark for bashunit webpage
Left is before, right is after with the new change. 
Add in style.css:
```css
.box {
background-color: #3b3c392e;
}
```
> Make boxes slightly less dark for the bashunit webpage

- .gitignore
- install.sh
The current `./bashunit` file depends on multiple other files to manage better the complexity of the project, spliting by responsibility, scope and context. However, it might be useful to be able to have the whole tool in one single file for installation purposes as third-party dependency.
- Create an `install.sh` script, which will create an executable of `bashunit` in one single file inside the `bin/` folder
>  I thought about this originally because of this issue: https://github.com/bpkg/bpkg/issues/168#issuecomment-1738304446 
This installer could help us solving this "missing deps files" when installing bashunit.
> Create one single bin executable

- CHANGELOG.md
- docs/assertions.md
- docs/getting-started.md
- example/logic_test.sh
- src/assert.sh
- src/test_doubles.sh
- tests/acceptance/bashunit_test.sh
- tests/functional/logic_test.sh
- tests/unit/assert_test.sh
- tests/unit/console_results_test.sh
- tests/unit/helpers_test.sh
- tests/unit/setup_teardown_test.sh
- tests/unit/test_doubles_test.sh
In bash, is common to use snake_case instead of camelCase. 
Therefore, the bash community will appreciate this.
- Create all assertions using snake_case
- Deprecate all assertions using camelCase; they will be remove in a future version
> Use snake_case assertions

- CHANGELOG.md
- src/assert.sh
- src/console_results.sh
- src/helpers.sh
- src/runner.sh
- src/state.sh
- src/test_doubles.sh
- tests/acceptance/bashunit_test.sh
- tests/functional/logic_test.sh
- tests/unit/assert_test.sh
- tests/unit/helpers_test.sh
- tests/unit/state_test.sh
I have created a new PR (coming from https://github.com/TypedDevs/bashunit/pull/105) from a new branch in this repository so now we can work together on it.
In case a test fails because an error inside, it will be marked as failed and it will show the result code error:
The main objective is execute the tests in a subshell with the `set -e`. The problem with this is that in the subshell we don't have access to the same state variables of the parent shell so we can't increase the assertion count from the subshell.
To avoid this problem, the idea is return (printing) the total of assertions failed and passed in the subshell and then in the main runner shell we have to parse this output and get the assertions failed and passed so we can increase them now in the main shell. 
There are some …
> Manage error when test execution fails

- CHANGELOG.md
- Makefile
- bashunit
- bin/pre-commit
- src/console_results.sh
- src/runner.sh
- tests/acceptance/bashunit_test.sh
Issue: https://github.com/TypedDevs/bashunit/issues/59: Display dots instead of tests names
Currently, the only output from bashunit is the test names in a `prettify way`. 
We want to allow rendering dots (a dot per test). 
- Render dots (per test) by default
- Render the scripts and test names using the new flag `--verbose`
> Output dots

- CHANGELOG.md
- build.sh
- install.sh
I want to make the installation of `bashunit` as simple as possible with just one command.
- Move the current `install.sh` to `build.sh`
- Create a new `install.sh` which can be used as a script bash file to install bashunit from anywhere using curl
Using the install.sh from this branch to install `bashunit` as a single file in another project
```bash
#!/bin/bash
curl -o _install.sh https://raw.githubusercontent.com/TypedDevs/bashunit/feat/install-and-build-scripts/install.sh
chmod +x _install.sh
./_install.sh
rm _install.sh
```
https://github.com/TypedDevs/bashunit/assets/5256287/80e31eb2-33a0-4568-a67d-c92164221ed2
> Install and build scripts

- CHANGELOG.md
- Makefile
- bashunit
- src/console_results.sh
- src/runner.sh
- tests/acceptance/bashunit_test.sh
This reverts commit dc89a22014d52025729f7f88ac8145a263118f95.
Use "verbose output" by default, and allow using `--simple` to display a simplified output using a dot per passed test.
> Use verbose output by default

- docs/.vitepress/config.ts
- docs/test-doubles.md
- src/test_doubles.sh
- tests/unit/test_doubles_test.sh
- On docs, i moved test doubles before assertions (similar order in PHPUnit and Jest).
- Changed docs/test-doubles.md general descriptions/examples to fit more with the other sections.
- Changed the fail output of assert_have_been_called and assert_have_been_called_times to be more developer-friendly
- Test assert_have_been_called_times fail output
> Little test doubles changes

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/directory_test.sh
Based on the new assert for files (https://github.com/TypedDevs/bashunit/pull/128), I have added new assert for directory:
- `assert_directory_exists`
- `assert_directory_not_exists`
- `assert_is_directory`
- `assert_is_directory_empty`
- `assert_is_directory_not_empty`
- `assert_is_directory_readable`
- `assert_is_directory_not_readable`
- `assert_is_directory_writable`
- `assert_is_directory_not_writable`
> Add assert for directory

- bashunit
- src/runner.sh
Refactor all the state function names to follow the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html)
Removed unused function (Runner::cleanSetUpAndTearDownAfterTest)
It's an internal refactor so I didn't added it to the CHANGELOG.md
> Refactor runner functions

- CHANGELOG.md
- install.sh
Currently, the installer accepts a concrete TAG or latest branch, but there is no possibility to install the `main` branch.
- Allow passing `main` to install the main branch similarly as with the `latest` branch
> Allow using main or latest when using install.sh

- docs/installation.md
Move `like npm for Javascript ...` text to a tooltip.
> docs: add tooltip in installation page

- CHANGELOG.md
- bashunit
- docs/command-line.md
- src/console_header.sh
- src/runner.sh
- Add `--help` option
- Display the help text if no argument is provided
> Create --help option

- CHANGELOG.md
- docs/test-files.md
- example/logic_test.sh
- src/helpers.sh
- src/runner.sh
- tests/functional/provider_test.sh
- tests/unit/helpers_test.sh
This is a **proof of concept** PR of a simple data provider for test functions.
The main idea is having an "annotation" just before the test function where we can specify the data provider function as this:
```
function test_my_function_test() {
...
}
```
This function_data_provider can return a single or a list of values. Those are two examples of data provider:
```
function provider_test_data_array() {
local data=("one" "two" "three")  
echo "${data[@]}" 
}
function provider_test_data_single_value() {
echo "one" 
}
```
The test function will receive the data provided in the $1 parameter.
> Data provider for test functions

- docs/assertions.md
- docs/command-line.md
- docs/quickstart.md
- docs/skipping-incomplete.md
- docs/test-doubles.md
- docs/test-files.md
Added code-groups to most of the code boxes in the documentation.
In all examples, the new version is on the left and the old one on the right.
Label more clearly what the box represents (in this case an example):
Identify which file is being worked on, which aids in skimming:
Allows grouping examples with their outputs, making the documentation less vertically extensive:
- Add code-groups.
- Remove the text format from the outputs (use none instead, it's more accurate).
> Add code-groups

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
- `assert_string_not_starts_with`
- `assert_string_starts_with`
> assert_string_not_starts_with & assert_string_starts_with

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
- `assert_string_ends_with`
- `assert_string_not_ends_with`
> Assert string ends with

- adrs/TEMPLATE.md
- adrs/adr-001-changing-error-detection-mechanism.md
- src/console_results.sh
- src/runner.sh
- tests/acceptance/bashunit_test.sh
"The objective of this PR is to change the behavior of how an error is detected within a test to mark it as failed.
Currently, the tests detected these errors using return codes along with set -e. The set -e makes a script (the test in this case) interrupt if any execution within the script returns an error code other than 0. This in theory sounds good since if something went wrong, the test execution was interrupted and marked as failed, but in practice, it is not so, since if a line executes several functions, only the return of the last one is counted, therefore for this common situation:
```bash
function test_a_non_existing_function_assert_empty() {
assert_empty "$(a_non_existing_function)"
}
```
The test no longer failed, since although a_non_existing_function returns an error 127, …
> feat: alternative to set -e

- docs/installation.md
Add instructions on how to install `bashunit` via MacPorts.
https://ports.macports.org/port/bashunit/
- Add entry to installation doc (`docs/installation.md`) detailing MacPorts installation of `bashunit`
> docs: add MacPorts install info

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
- Added `assert_equals_ignore_colors`
> Add assert_equals_ignore_colors

- CHANGELOG.md
- src/console_results.sh
- src/runner.sh
- tests/unit/console_results_test.sh
Issue: https://github.com/TypedDevs/bashunit/issues/203 ; `Milestone 1`
- Print, in parentheses to the right of the name of the test, the arguments with which it is being provided
> Improve data provider output

- Makefile
- bashunit
- src/helpers.sh
- src/runner.sh
- tests/unit/helpers_test.sh
Follow up after https://github.com/TypedDevs/bashunit/pull/205
- Remove `read_and_store_files_recursive()` in favor of using just `find_files_recursive()`
- Fix `make test` script
> Fix wildcards tests

- tests/unit/assert_snapshot_test.sh
The unit tests on macOS was broken due to a typo on one snapshot test. [See CI](https://github.com/TypedDevs/bashunit/actions/runs/6805316312/job/18504570525).
- Fix `test_creates_a_snapshot` for macOS
> Fix test_creates_a_snapshot for macOS

- CHANGELOG.md
- install.sh
- tests/acceptance/install_test.sh
You can download and install the current beta from the main branch. However, currently there is no way to know when did you get that beta, so it can be confused to know which version contains as latest.
- When installing a beta version, append the current date; helpful to distinguish between different beta versions, so you will be able to know WHEN did you get that beta version.
> Add current date on beta installation version

- CHANGELOG.md
- bashunit
- docs/command-line.md
- src/console_header.sh
- src/helpers.sh
- src/upgrade.sh
- tests/acceptance/bashunit_upgrade_test.sh
- tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
- tests/acceptance/upgrade_bashunit_test.sh
- tests/unit/helpers_test.sh
> Upgrade option

- src/helpers.sh
- src/runner.sh
By removing the call to the deprecated setUp/tearDown functions and modifying the implementation of the execute_function_if_exists and unset_if_exists helpers, I've managed to reduce the execution time of the library's own tests by around 15% in my local environment.
To calculate these times, I have been running the following script while making changes and taking an average of the times:
```bash
for i in {1..10}; do make test | grep "Time taken: " >> result_2_f; done
```
After all the changes, the results I have obtained from main vs this branch are as follows:
Removing the deprecations meant a reduction of about 5%, and modifying the implementation of the helpers accounted for the remaining 10% reduction.
- Remove support to deprecated setUp/tearDown functions
- Optimize test execution …
> Optimize bashunit

- docs/installation.md
The git submodule option downloads the whole repo, which contains files/folders that are not needed at all (eg: the docs folder, among others). This was originally an idea before we created the build.sh and install.sh, or even the online [installer tool](https://bashunit.typeddevs.com/installation#install-sh). I would aim to simplify the docs site removing its section from the docs.
- Remove the "Git submodule" from [installation](https://bashunit.typeddevs.com/installation) section
> docs: Remove Git submodule

- Makefile
The Git repository is not always ".git" - for example, if this repository is a submodule or worktree, or if $GIT_DIR is set explicitly.
- Updates the Makefile to use `git rev-parse --git-dir` to find the real directory.
(This didn't seem like a big enough change to merit either of these.)
> Copy pre-commit hook to real GIT_DIR

- docs/examples.md
[phpclt ](https://github.com/opencodeco/phpctl)is a CLI tool that works as a set of Bash scripts for a container-based development environment for PHP and its tested using bashunit.
This PR adds the project to the examples listing in the docs.
- Adding a new level-3 heading to the `docs/example.md` file.
> Add phpctl to the examples page

- build.sh
Update the release script so the final bashunit script will use PATH to find bash. The version of bash in /bin on macOS is very old, and forcing tests to use it is quite limiting.
- Change `build.sh` so it prepends `#!/usr/bin/env bash` to the final `bashunit` script.
> fix: use the bash executable specified by PATH

- .github/RELEASE.md
- install.sh
Remove downtime on install latest #225
1. Updated install.sh to fetch the latest version from the git hub instead of hard coding.
2. Updated RELEASE.md file.
> added get_latest_tag in install.sh

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- src/console_results.sh
- tests/unit/assert_test.sh
Adds new `fail()` function for general purpose test failures not covered by the various `assert_*` functions.
- Added `fail()` function in assert.sh
- Added `console_results::print_failure_message()` function in console_results.sh
- Added test case
> chore: add fail() function

- CHANGELOG.md
- tests/acceptance/bashunit_upgrade_test.sh
Replace this text with a short description of your feature/bugfix.
Fix failing test due to the way `sed` command behave in macOS, sometimes the file `./bin/bashunit-e` isn't created  and the test fails:
To avoid this I've added the `-f` flag to the `rm` command to in case the `./bin/bashunit-e` don't exist the command don't fail and breaks the test, doc related:
- Add `-f` flag to avoid problems with `rm` command in macOS
> fix: `bashunit-e` file isn't created sometimes

- CHANGELOG.md
- tests/acceptance/install_test.sh
Add assertions request in  `todo`
- Assert number of files in installed directory
- Assert the only file in installed directory is the `bashunit` file
> Add missing assertions in non-stable version test

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
Implement new `assert_line_count` assertion function.
refs https://github.com/TypedDevs/bashunit/issues/257
- Add `assert_line_count`
> Add `assert_line_count`

- CHANGELOG.md
- install.sh
- tests/acceptance/install_test.sh
Right now when installing a beta release, you see only the date. I would like to see the latest stable release as well.
- Add `after X.Y.Z` release when installing a beta release
> Add LATEST_BASHUNIT_VERSION when installing beta

- src/main.sh
- tests/acceptance/snapshots/bashunit_direct_fn_call_test_sh.test_bashunit_direct_fn_call_failure.snapshot
- Show assert function name instead of "Main::exec assert"
> Improve assert function standalone

- src/assert.sh
- tests/unit/assert_test.sh
Related to: https://github.com/phpstan/phpstan-src/pull/3160#discussion_r1643031961 
> The `\n` are ignored when counting the lines `actual=$(echo "$input_str" | wc -l | tr -d '[:blank:]')`
- Count additionally the `\n` of a string on `assert_line_count`
> Fix: assert_line_count

- src/assert.sh
- src/main.sh
- tests/acceptance/bashunit_direct_fn_call_test.sh
- tests/acceptance/snapshots/bashunit_direct_fn_call_test_sh.test_bashunit_direct_fn_call_failure.snapshot
Issue: https://github.com/phpstan/phpstan-src/pull/3160#discussion_r1643902055
Multiline strings are passes as multiple args to `assert_line_count` which makes it complicated to pass around and manipulate as unique string.
- `assert_line_count` uses first arg for the expected and the rest (think about a `variadic ...string arg`) will be the string itself that will be use to count its lines.
Tradeoff: I had to rollback https://github.com/TypedDevs/bashunit/pull/262 in order to make it working. I think I can make it back again, but it might take another couple of hours... so, I thought to ship this first, make it work, and then in a follow up make it better.
> fix: assert_line_count on multiline

- src/assert.sh
- tests/acceptance/bashunit_direct_fn_call_test.sh
Related: https://github.com/phpstan/phpstan-src/actions/runs/9567238902/job/26374488151 
> Thanks for the support and help @staabm
- Remove the optional label and use always `label="$(helper::normalize_test_function_name "${FUNCNAME[1]}")"`, which is something we are using all around and it makes sense to keep it this way
- For string arguments, use all arguments but the first one (reserved for the expected)
- `assert_equals` on multiline strings does not work, because multilines takes mutiple arguments positions when passing to other functions... so it's bash - at least I didn't find another solution for this problem so far.
- This means that, multiline strings will work as last argument as they are treated as variadic arguments like `...string`, therefore the first argument must be `one …
> Fix: multistring assertions

- CHANGELOG.md
- install.sh
- tests/acceptance/install_test.sh
Closes: https://github.com/TypedDevs/bashunit/issues/261
Show the current hash next to the `version` command in beta.
> Add hash next to version in beta

- CHANGELOG.md
- docs/installation.md
Closes: https://github.com/TypedDevs/bashunit/issues/256 by @staabm
- Add new section "GitHub Actions" to installation documentation
> Add GitHub Actions to installation doc

- src/main.sh
- tests/acceptance/bashunit_direct_fn_call_test.sh
In bash, when a function does not exist, the exist code must be `127`
- Do `exit 127` on `exec_assert()` when function does not exist
> Fix: exit code when fn does not exist

- CHANGELOG.md
- src/runner.sh
- tests/unit/redirect_error_test.sh
This PR is for solving the issue https://github.com/TypedDevs/bashunit/issues/272
Echo statement with a new line inside a test was breaking the test execution result data and the head pipe on this variable was getting the echoed data and not the test execution result. As the test execution result data will be always at the last line, changing `head` to `tail` could resolve this issue.
> fix: echo does not break test execution result

- CHANGELOG.md
- bashunit
- docs/.vitepress/config.ts
- docs/custom-asserts.md
- src/bashunit.sh
- tests/functional/custom_asserts.sh
- tests/functional/custom_asserts_test.sh
- Add bashunit facade to enable custom assertions
- `bashunit::assertion_failed()`
- `bashunit::assertion_passed()`
> Enable simple custom assertions

- .github/RELEASE.md
- .gitignore
- CHANGELOG.md
- docs/installation.md
- package.json
Closes: https://github.com/TypedDevs/bashunit/issues/277
- Add checksum to `package.js`
- Document how to check the sha256sum as part of the installation (optional step)
- The docs will show a one liner command to check the latest checksum effortless 
https://github.com/TypedDevs/bashunit/assets/5256287/e6e7a27a-b667-4171-86f6-81f2445d606e
I added the checksum for all GitHub releases `>=0.8`.
> Document how to verify the sha256sum of the final executable

- CHANGELOG.md
- src/clock.sh
- tests/unit/clock_test.sh
- tests/unit/console_results_test.sh
Here https://github.com/TypedDevs/bashunit/pull/279 ([diff](https://github.com/TypedDevs/bashunit/pull/279/files#diff-4a7672be1d0d2231ed4f311f4f82104470065074a0e9241fb52d4ce5bd1f617dL108)) we found a way to enable the exec time for all OS, however it's depending on `perl`. It is very unluckily that it's not installed by default, but in case it wouldn't be installed it would be interesting to use the old logic using `date` - which is something that all OS should have with more probability than `perl`.
- Use `date` to get the time in case `perl` is not installed
> Support displaying clock without perl (for non-macOS)

- CHANGELOG.md
- build.sh
When creating a new release, you need to generate the checksum after doing the build and use it in different places. This PR is helping into automating the generation of the checksum so there is one manual step less to do.
- Improve build script to generate the checksum (sha256) automatically
- Only in macOS and Linux
https://github.com/user-attachments/assets/8d9adddf-d365-4120-b23b-84b5cf9d9414
> Generate checksum on build

- CHANGELOG.md
- bashunit
- docs/command-line.md
- src/console_header.sh
- tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
- tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot
This is useful to understand when a script is stuck in some place but there is no visual output, so you have no feedback of what's going on. Debugging mode gives you all level of details of what's happening, enabling you to understand what's going on in the _darkness_ 🐐 
- Add `--debug` option using `set -x`
... etc
> Debug option

- bashunit
- src/logger.sh
- move time attr to unique line
- simplify case in entrypoint reducing shifts
---
> shift is a bash built-in which kind of removes arguments from the beginning of the argument list. Given that the 3 arguments provided to the script are available in $1, $2, $3, then a call to shift will make $2 the new $1. A shift 2 will shift by two making new $1 the old $3.
> source: https://unix.stackexchange.com/a/174568
> Reducing shifts in entrypoint

- CHANGELOG.md
- src/logger.sh
- src/runner.sh
- src/state.sh
- tests/unit/state_test.sh
Closes https://github.com/TypedDevs/bashunit/issues/288 
- Add a new property for each testsuite like assertions="\d" with the total of assertions passed for each test.
> Add assertions to log file

- tests/unit/state_test.sh
_CamelCase_ methods were deprecated in a previous bashunit version, this PR aims to remove all _CamelCase_ test methods in the project by the _snake_case_ version.
> Remove deprecated uppercase methods on state_test file

- CHANGELOG.md
- src/helpers.sh
- tests/functional/multi_invoker_test.sh
- tests/unit/helpers_test.sh
- fixes #299 
I added `*` in `${prefix}_*${filter}`  within function `helper::get_functions_to_run` to keep the match more dynamic even if it's not exactly after the prefix (test). 
---
Ran Tests Locally to verify changes within the scope of [`state_test`](https://github.com/TypedDevs/bashunit/blob/main/tests/unit/state_test.sh) file.
1.  Test with a matching string `assertions`  inside the function name (9 functions have it) ✅ 
```bash
╰─$  ./bashunit tests/unit/state_test.sh -f assertions                                                         
bashunit - 0.14.0
Running tests/unit/state_test.sh
✓ Passed: Add and get assertions passed
✓ Passed: Add and get assertions failed
✓ Passed: Add and get assertions skipped
✓ Passed: Add and get assertions incomplete
✓ Passed: Add and get …
```
> Fix filter matching pattern with and without `test` prefix

- CHANGELOG.md
- bashunit
- docs/command-line.md
- docs/configuration.md
The `-v` is commonly used for `--version` while for verbose is more common to use `-vvv`
- Little change affecting the command shortcuts for version (-v) and verbose (-vvv)
> Use -v for version and -vvv for verbose

- CHANGELOG.md
- install.sh
Closes #315
The commit displayed when checking the bashunit version should be from the last commit from bashunit, not the proyect installing bashunit.
- List individual changes in more detail
> Fix wrong commit id when installing beta

- src/clock.sh
Fix: #318 
bashunit will throw an error when Perl Time::Hires is not available. This requires a minor fix to the clock::now() function.
```
function clock::now() {
if perl -MTime::HiRes -e "" > /dev/null 2>&1; then
perl -MTime::HiRes -e 'printf("%.0f\n",Time::HiRes::time()*1000)'
elif [[ "$_OS" != "OSX" ]]; then
date +%s%N
else
echo ""
fi
}
```
> Fix clock::now() Can't locate Time/HiRes.pm

- CHANGELOG.md
- src/runner.sh
Fixes: https://github.com/TypedDevs/bashunit/issues/309 by @mkonig
Right now, when using a not found command in a test, this is ignored and makes the test pass as all good... This makes TDD impossible by definition. 
> We need to allow starting with a failing test writing what we want to have before having it.
This should fail! 🙃 
- Check in the test_execution_result if contains "command not found" in such a case extract the error msg and render it as a failing test
> Fixed failing tests with command not found

- CHANGELOG.md
- docs/assertions.md
- src/assert_files.sh
- src/assert_snapshot.sh
- src/runner.sh
- tests/unit/file_test.sh
Closes: https://github.com/TypedDevs/bashunit/issues/322 by @staabm
- Add `assert_files_equals`
- Add `assert_files_not_equals`
- Fixed "unbound variable" on runtime error message
https://github.com/user-attachments/assets/31828c38-e676-48ed-9729-12ddc43038eb
> Added assert_files_equals

- CHANGELOG.md
- src/console_header.sh
- src/helpers.sh
- src/main.sh
Fixes: https://github.com/TypedDevs/bashunit/issues/320
- Use filter when calculating the total tests header
> Use filter when calculating the total tests header

- .gitignore
- CHANGELOG.md
- bashunit
- docs/command-line.md
- src/console_header.sh
- tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
- tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot
Inspired by wanting debug this in an easier way https://github.com/TypedDevs/bashunit/issues/305#issuecomment-2365045807 @staabm 
- Add optional file-path as 2nd arg to `--debug` option
```bash
./bashunit local/example_test.sh --debug > local/debug.sh 2>&1
```
```bash
./bashunit local/example_test.sh --debug local/debug.sh
```
> Improve debug output

- .github/workflows/tests.yml
- CHANGELOG.md
- Makefile
- src/console_results.sh
- src/default_env_config.sh
- src/main.sh
- src/runner.sh
- src/state.sh
- tests/acceptance/bashunit_report_html_test.sh
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_env.snapshot
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_option.snapshot
- tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_env.snapshot
- tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_option.snapshot
- tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_env.snapshot
- tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_option.snapshot
- tests/unit/file_test.sh
- tests/unit/state_test.sh
Closes: https://github.com/TypedDevs/bashunit/issues/294
- Better handler runtime errors
- Have control over the single-test-outcomes
- Do not use FD 3 when executing the test function. Instead, add the test output to the `subshell context`
-  Save the failing tests into a temporal file so that we can render them at the end of the runner
> Display failing tests again

- src/console_results.sh
- src/default_env_config.sh
- src/str.sh
- tests/unit/str_test.sh
- Render the execution test-time on the same line - at the very end of the terminal.
- If the line is too long, then cut it and use `...` to create awareness the test name is larger than what you see
- Simplify the test duration: from `(123 ms)` to `123 ms`
> Improve test duration output 

- CHANGELOG.md
- bashunit
- docs/standalone.md
- src/assert.sh
- src/main.sh
- tests/acceptance/bashunit_direct_fn_call_test.sh
Closes: https://github.com/TypedDevs/bashunit/issues/334
- Allow defer calling a function when asserting `exit_code` by passing the callable command to evaluate as raw string instead of `$(...)`
- bashunit output will be render on the stderr
Render the stdout in the terminal and the errors in a file
```bash
export PHPSTAN_PATH=[...]/vendor/bin/phpstan
../bashunit -a exit_code "1" "$PHPSTAN_PATH analyze --no-progress --level 8 --error-format raw ./"
echo $?
../bashunit -a exit_code "0" "$PHPSTAN_PATH analyze --no-progress --level 8 --error-format raw ./"
echo $?
../bashunit -a exit_code "0" "$PHPSTAN_PATH analyze --no-progress --level 8 --error-format raw ./" 2> /tmp/error.log
cat /tmp/error.log
```
> Make asserting failed exit codes and output nicer

- CHANGELOG.md
- bashunit
- src/globals.sh
- src/main.sh
- tests/acceptance/bashunit_direct_fn_call_test.sh
- tests/unit/directory_test.sh
- Improved `temp_file` and `temp_dir`
- Call `cleanup_temp_files` at the end of bashunit > `main::exec()`
- Use `temp_file` instead of `mktemp` for better cleanup
> Better cleanup temporal files

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
- tests/unit/state_test.sh
- Add `assert_true`
- Add `assert_false`
> Add assert_true and assert_false

- docs/installation.md
I have created a new project: "A simple dependency manager for bash" named [bashdep](https://github.com/Chemaclass/bashdep)
- Add `bashdep` to the installation page: https://bashunit.typeddevs.com/installation
> Usage example: https://github.com/Chemaclass/bash-skeleton/blob/main/install-dependencies.sh
> Add bashdep to installation

- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
Follow up after: https://github.com/TypedDevs/bashunit/pull/350
Idea by @skinner-m-c -> https://github.com/TypedDevs/bashunit/pull/350#discussion_r1788722180
- Improve `assert_true` and `assert_false`
- Consider passing a function/command/alias that will resolve into true or false
> Improve assert true/false accepting callable as arg

- .github/workflows/tests.yml
- CHANGELOG.md
- src/console_results.sh
- src/globals.sh
- tests/unit/console_results_test.sh
- tests/unit/globals_test.sh
Windows CI tests need to be faster. I want to explore ways to speed it up.
- Run different test dir (acceptance, functional, unit) in parallel
> Improve CI tests runtime (halved)

- src/globals.sh
When running on my macos 2017 with my default bash, my `tests/unit/directory_test.sh` are failing
```
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin22)
Copyright (C) 2007 Free Software Foundation, Inc.
```
- Fix `directory_test`
> fix: use mktemp compatible bash 3.2

- CHANGELOG.md
- install.sh
Fixes #359 
- Add check that git is installed to `install.sh`
The first place to use the `git` command in `install.sh` was the `get_latest_tag` function.
Before calling `get_latest_tag`, a check had to be made.
> fix: add check that git is installed to `install.sh`

- build.sh
- tests/unit/debug_test.sh
The build right now append all files from `src/*.sh` in alphabetical order. 
However, the sourcing order is important (same as it is defined in the entry-point `./bashunit`.
- Define an order how to "source" the src files when building the project with `./build.sh`
> Improve build

- .github/RELEASE.md
- CHANGELOG.md
- install.sh
- tests/acceptance/install_test.sh
Related: https://github.com/TypedDevs/bashunit/issues/359#issuecomment-2407947718 CC: @smeghead 
- Remove git dependency from stable installation
> However, git is required when installing beta, because it is downloading and building the project from lastest main
> Improve installer

- .github/workflows/tests.yml
- CHANGELOG.md
- Makefile
- src/globals.sh
- src/main.sh
- src/parallel.sh
- src/runner.sh
- src/state.sh
- tests/unit/globals_test.sh
- Enable parallel tests only for macOS and Ubuntu
- Disabled for windows and linux/alpine due to their inconsistent results - mostly due to race conditions
- Improve the tests CI
> Parallel feature flag enabled for macOS and Ubuntu

- src/globals.sh
- src/runner.sh
- src/state.sh
- tests/unit/state_test.sh
- remove the test_id that I added on the assertions' internal output
- make global `random_str` non dependent on external tools
> Fix tr warning on ubuntu's CI

- CHANGELOG.md
- src/assert.sh
- tests/unit/assert_test.sh
Add `assert_not_same` function
Fixes #372 
- rename assert_not_equals to assert_not_same (and all its usages)
- add a new assert_not_equals (look at assert_equals and use opposite condition)
> Add `assert_not_same` function

- src/runner.sh
- tests/acceptance/bashunit_execution_error_test.sh
- tests/acceptance/fixtures/test_bashunit_when_a_execution_error.sh
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_env.snapshot
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_option.snapshot
- tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_with_wildcard.snapshot
- tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_directory.snapshot
- tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_file.snapshot
- tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_env.snapshot
- tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_option.snapshot
- tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_verbose_output_env.snapshot
- tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_verbose_output_option.snapshot
- tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_argument_path.snapshot
- tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_env_default_path.snapshot
- tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_env.snapshot
- tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_option.snapshot
- tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_env.snapshot
- tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_option.snapshot
- Add the `Running $script` text always when verbose is enabled
- Make it bold
> Improve render file header on verbose

- CHANGELOG.md
- src/helpers.sh
- tests/unit/helpers_test.sh
Fixes: https://github.com/TypedDevs/bashunit/issues/387
-Adapt `helper::normalize_test_function_name` for test functions that want `test` to be render
> Fix display name when test_test_*

- CHANGELOG.md
- src/globals.sh
- src/runner.sh
- tests/acceptance/bashunit_fail_test.sh
- tests/acceptance/fixtures/test_bashunit_with_multiple_failing_tests.sh
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_with_multiple_failing_tests.snapshot
Fixes: https://github.com/TypedDevs/bashunit/issues/381
- Add caller source and line to `log` (global function)
- Fix displaying errors on multiline
> Fix display multiline errors within the same test

- docs/examples.md
Hi,
There are some updates in the name and URL. The org on Github is now called SherpaCLI and the Netlify subdomain sherpa-cli. Shorter and more decriptive.
Moved from Astro to NuxtJS for the new website. 
_Out of curiosity... Any idea of the scheduled published date of the updated 'examples' page? The live one on [bashunit.typeddevs.com](https://bashunit.typeddevs.com/examples) seems to mention "Last updated: 09/11/2024" in the footer._
Updating a link after naming and subdomain changes.
> New subdomain and orgName for Sh:erpa

- src/helpers.sh
- tests/unit/fixtures/no_function_keyword_duplicates.sh
- tests/unit/helpers_test.sh
The previous implementation assumed that function names would always be in the second field when using awk to extract them. This caused issues when the function keyword was omitted, as the function name could be in any field.
This fix:
1. Scans all fields in each line for a pattern matching a test function name
2. Uses a proper regex pattern to identify function names
3. Only processes and prints actual function names
4. Adds an explicit return 0 for clarity
Added test case to verify the fix works with function declarations that omit the function keyword.
> fix: improve duplicate function detection to handle functions without function keyword

- CHANGELOG.md
- src/runner.sh
- src/state.sh
- tests/acceptance/bashunit_fail_test.sh
- tests/acceptance/fixtures/test_bashunit_when_exit_immediately_after_execution_error.sh
- tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_with_a_test_fail_and_exit_immediately.snapshot
- tests/unit/state_test.sh
Fixes: https://github.com/TypedDevs/bashunit/issues/390
- Traps the exit code when running a test
🖼️ Demo
**Before**
**After**
> Fix false negative with `set -e`

- tests/unit/clock_test.sh
- tests/unit/console_results_test.sh
Fixes #396.
Only run the macos related tests on macos and skip on linux so that all tests pass.
> fix: only run macos related tests on macos

- src/console_results.sh
Bash's built-in `printf` does not support floating-point formats like `%f`. This causes errors such as 'invalid number' when formatting values like `167.183`.
- This commit update the usage of `printf` with `awk`, which correctly handles float rounding and improves portability across platforms including GNU Bash.
> fix: avoid printf error on floating-point values by using awk

- src/runner.sh
- src/test_doubles.sh
- tests/acceptance/fixtures/test_parallel_spy_file1.sh
- tests/acceptance/fixtures/test_parallel_spy_file2.sh
- tests/acceptance/parallel_spy_parallel_test.sh
- scope spy temp files by test id
- expose current test id to spies via `BASHUNIT_CURRENT_TEST_ID`
- add a regression test covering spies running in parallel
- `./bashunit tests/unit/test_doubles_test.sh tests/acceptance/parallel_spy_parallel_test.sh`
- `./bashunit --parallel tests/unit/test_doubles_test.sh tests/acceptance/parallel_spy_parallel_test.sh`
> Fix parallel spy temp file conflicts

- CHANGELOG.md
- docs/test-doubles.md
- src/runner.sh
- ensure each test run has a unique id for test doubles
- document parallel friendly spy files
- note the fix in the changelog
> Fix parallel test doubles

- CHANGELOG.md
- adrs/adr-004-metadata-prefix.md
- docs/blog/2024-09-01-release-0-15.md
- docs/data-providers.md
- src/helpers.sh
- tests/functional/provider_test.sh
- tests/unit/assert_test.sh
- tests/unit/check_os_test.sh
- tests/unit/helpers_test.sh
Data providers are defined via a special comment `# data_provider`. We want to clearly differentiate these meta comments from ordinary comments.
> Deprecate data_provider in favor of @data_provider

- .github/workflows/tests.yml
- CHANGELOG.md
- docs/command-line.md
- src/main.sh
- src/parallel.sh
- tests/unit/parallel_test.sh
- enable parallel mode for Windows
- update docs and CI workflow
- add a unit test for parallel::is_enabled on Windows
- document change in changelog
> Enable parallel tests on Windows

- CHANGELOG.md
- src/runner.sh
- Calculate assertions with regex instead of subshells for each number
> Optimize runner

- docs/.vitepress/config.ts
This PR fixes an issue where {{ $frontmatter.* }} variables were not being interpolated in the Markdown content during the local search index generation, leading to incomplete or incorrect entries.
- Applied frontmatter variable interpolation to rendered HTML before indexing
-
> docs/fix: interpolate frontmatter variables during local search index generation

- bashunit
- docs/benchmarks.md
- src/benchmark.sh
- src/env.sh
- src/globals.sh
- src/runner.sh
- tests/benchmark/bashunit_bench.sh
- tests/benchmark/fixtures/bashunit_functional_bench.sh
- tests/benchmark/fixtures/bashunit_sleep_bench.sh
- tests/unit/benchmark_test.sh
I want to enable assertions on threshold time in ms on max avg time on a benchmark test
- Add "max_ns" metadata (as an assertion) to display red the benchmark 
- Eg: `@max_ns=100`
> Add max_ms option on bench

- bashunit
- src/benchmark.sh
- tests/unit/benchmark_test.sh
- Load the benchmark module only when using benchmark tests
> Improve bench loading

- CHANGELOG.md
- docs/installation.md
- install.sh
- tests/acceptance/install_test.sh
RIght now, to install a [custom version](https://bashunit.typeddevs.com/installation#define-custom-tag-and-folder), you have to define the directory
```bash
curl -s https://bashunit.typeddevs.com/install.sh | bash -s [dir] [version]
```
- Allow using `install.sh` with only a version argument or both arguments in any order
```bash
curl -s https://bashunit.typeddevs.com/install.sh | bash -s [dir]
curl -s https://bashunit.typeddevs.com/install.sh | bash -s [dir] [version]
curl -s https://bashunit.typeddevs.com/install.sh | bash -s [version]
curl -s https://bashunit.typeddevs.com/install.sh | bash -s [version] [dir] 
```
> Make installer args more flexible

- CHANGELOG.md
- src/check_os.sh
- tests/unit/check_os_test.sh
- detect more Windows environments (MSYS, Cygwin) in `check_os::is_windows`
- extend unit tests for Windows detection
- document improved Windows detection in changelog
> Improve Windows detection for parallel tests

- CHANGELOG.md
- src/runner.sh
Fix https://github.com/TypedDevs/bashunit/issues/433
- Fix `runner::parse_result_parallel` template
> Fix parallel consistency on arch64

- .github/workflows/tests.yml
- CHANGELOG.md
Related: https://github.com/TypedDevs/bashunit/issues/433
- Add more CI tests for diff versions of ubuntu and macos to improve the test coverage in diff OS
> Split macos and ubuntu ci jobs

- CHANGELOG.md
- src/clock.sh
- tests/unit/clock_test.sh
Fixes: #436
Processing time is always shows as 0 ms in version 0.21.0, it was displayed correctly in version 0.20.0
- Keep same order as in v0.20.0
> Fix process time always shows as '0 ms'

- CHANGELOG.md
- bashunit
- build.sh
- docs/command-line.md
- src/init.sh
- tests/acceptance/bashunit_init_test.sh
Right now, we have documented how to start with bashunit step by step (see: https://bashunit.typeddevs.com/quickstart#usage), but I thought we could simplify even more with an `--init` option to create the initial setup and faster "onboarding" 🚀 
- Added a new initialization command that introduces a `--init` option for faster project setup
- Created an initialization script that prepares a bootstrap file and sample test for newcomers
- Documented the new --init option in the command-line guide
- Implemented an acceptance test validating that the initialization command generates the expected files
> Add --init option to get you started quickly

- tests/unit/assert_snapshot_test.sh
This fix https://github.com/TypedDevs/bashunit/issues/447
> fix: prevent writing in source directory during tests

- CHANGELOG.md
- src/assert_snapshot.sh
- src/str.sh
- tests/unit/str_test.sh
- Fix rpad so negative widths no longer cause substring errors
> Fix negative widths with rpad

- CHANGELOG.md
- src/assert.sh
- tests/unit/assert_test.sh
- Improve suffix assertion checks to use shell pattern matching
> Improve suffix assertion checks

- CHANGELOG.md
- Makefile
- src/env.sh
- src/globals.sh
- src/math.sh
- src/parallel.sh
- src/runner.sh
- tests/acceptance/bashunit_init_test.sh
- tests/acceptance/parallel_spy_parallel_test.sh
- tests/unit/clock_test.sh
- tests/unit/console_results_test.sh
CC @drupol 
- Temporary files now respect `$TMPDIR`, ensuring writable directories during Nix builds
- Parallel test directories likewise use `$TMPDIR` for compatibility with sandboxed environments
- Test targets explicitly run bashunit with bash, avoiding shell mismatch issues during package checks
- Replaced the reliance on `compgen` with a safer globbing approach so parallel result aggregation works even when programmable completion isn’t available
- Updated `math::calculate` to fall back to native shell arithmetic when `bc` or` awk` missing, avoiding precision loss
> Fix parallel and compgen issue on NixOS

- .github/CONTRIBUTING.md
- CHANGELOG.md
- install.sh
- shell.nix
- src/assert_snapshot.sh
- src/console_results.sh
- src/env.sh
- src/helpers.sh
- src/math.sh
- tests/acceptance/bashunit_upgrade_test.sh
- tests/acceptance/install_test.sh
- tests/unit/assert_snapshot_test.sh
- add `shell.nix` and document how to use NixOS to run `bashunit`
- use `command -v` instead of `which`
> @drupol thanks for the help with [NixOS](https://nixos.org/)!
Running with my local bash and within a nix-shell
```bash
nix-shell --pure -p bash --run "./bashunit --simple --parallel"  # with bash package
nix-shell --pure --run "./bashunit --simple --parallel"          # with `shell.nix` config
./bashunit --simple --parallel                                   # local
```
> Fix NixOS support

- CHANGELOG.md
- tests/acceptance/bashunit_init_test.sh
When ` nix run github:NixOS/nixpkgs#bashunit -- -v` using `bashunit 0.22.3` I get an error for the --init tests due to lack of permission to create directory/files // CC @drupol 
- Skip `--init` option tests for NixOS
> Skip --init option tests for NixOS

- CHANGELOG.md
- tests/acceptance/bashunit_init_test.sh
Reverts TypedDevs/bashunit#458
> Revert "Skip --init option tests for NixOS"

- CHANGELOG.md
- docs/test-doubles.md
- Documented how to mock function output using a here-string and a here-document, clarifying when each should be used
- Included an example demonstrating a multi-line output mock with a here-document
> Kudos to @akinomyoga who found it.
> Update docs for mock usage

- CHANGELOG.md
- README.md
- bashunit
- docs/installation.md
- tests/unit/bash_version_test.sh
Add support for detecting the minimum Bash version and exiting gracefully if unsupported.
> Idea from @akinomyoga, thanks!
- Documented the minimum Bash requirement in the README, stating that bashunit requires Bash 3.2 or newer
- Added a “Requirements” section in the installation guide with the same version information
- Implemented a runtime version check in the bashunit entrypoint to exit if the Bash version is below 3.2
- Logged this new feature in the changelog under Unreleased
- Created a new unit test ensuring bashunit exits with an error for unsupported versions
Add support for *Bash 3.0* and newer
> Add minimum supported Bash version check

- CHANGELOG.md
- src/clock.sh
- tests/unit/clock_test.sh
- Very last fallback: seconds resolution only
> Add fallback for clock with seconds resolution only

- CHANGELOG.md
- docs/assertions.md
- src/assert.sh
- tests/unit/assert_test.sh
Related https://github.com/TypedDevs/bashunit/issues/466 
> Idea from @akinomyoga, thanks!
- Introduced a new assert_exec helper that executes a command, captures exit status, stdout, and stderr, and validates all expectations together for concise command checks
- Added unit tests demonstrating successful and failing scenarios for assert_exec, ensuring coverage of exit codes and output assertions
- Documented assert_exec usage and options in the assertions guide so users can quickly adopt the new helper
- Updated the changelog to highlight the new consolidated execution assertion in the unreleased notes
> Add new assert_exec

- CHANGELOG.md
- docs/test-doubles.md
- src/test_doubles.sh
- tests/unit/dependencies_test.sh
- tests/unit/test_doubles_test.sh
Resolves https://github.com/TypedDevs/bashunit/issues/465 by @akinomyoga
- Enhanced spies to record both raw and serialized arguments, preserving args boundaries for reliable comparisons
- Reworked `assert_have_been_called_with` to accept the spy name first
- Updated docs and examples to describe the new --strict behavior and clarify how argument boundaries are handled
> Improve assert_have_been_called_with arg matching

- CHANGELOG.md
- docs/installation.md
- docs/quickstart.md
Related https://github.com/TypedDevs/bashunit/issues/476
Make Windows Install clearer
**Before:**
---
**AFTER:**
Linux/Mac
Windows:
> docs: Make Windows install clearer

- CHANGELOG.md
- docs/globals.md
Resolves https://github.com/TypedDevs/bashunit/issues/480
> Doc workaround for global name collisions

- CHANGELOG.md
- docs/globals.md
- src/globals.sh
- src/helpers.sh
- src/main.sh
- src/runner.sh
- tests/acceptance/bashunit_script_temp_file_cleanup_test.sh
- tests/acceptance/fixtures/script_with_setup_temp_file.sh
- tests/unit/globals_test.sh
Fixes #482
This PR resolves an issue where temporary files and directories created in `set_up_before_script` were not properly cleaned up.
It adds both a unit test an an acceptance test that fail without the fix and now pass.
* Extend `temp_file` and `temp_dir` functions so that they
* detect whether they are called in testcase context or script setup context
* use different target paths for each
* Improve clean up routines to
* clean up testcase temp data at the end of a test case
* clean up script temp data at the end of a test script (using different implementations for sequential and parallel modes)
> Always correctly clean up temp contents

- CHANGELOG.md
- src/main.sh
- src/parallel.sh
- tests/acceptance/bashunit_script_temp_file_cleanup_test.sh
This PR resolves an issue where temporary files and directories bashunit creates implicitly during a parallel run were not properly cleaned up.
It adds both a unit test an an acceptance test that fail without the fix and now pass.
This issue already existed before my changes in #483 .
- Add a new function `parallel::cleanup` and call it in each exit point when parallel mode is enabled
*Side note*: the previous `parallel::reset` function (which I renamed to `parallel::init` now) contained the following line:
```bash
[ -f "$TEMP_FILE_PARALLEL_STOP_ON_FAILURE" ] && rm "$TEMP_FILE_PARALLEL_STOP_ON_FAILURE"
```
IMO the condition `[ -f "$TEMP_FILE_PARALLEL_STOP_ON_FAILURE" ]` could never be true, as the containing directory is deleted right before the line. Hence I removed it. If it served any …
> Fix: clean parallel temp folder after test run

- .gitattributes
- .github/copilot-instructions.md
- .gitignore
- .tasks/.gitkeep
- AGENTS.md
- CHANGELOG.md
- README.md
- adrs/adr-005-copilot-instruction-or-spec-kit.md
Introduce a comprehensive `copilot-instructions.md` tailored for **bashunit** and our **TDD-first** workflow. It formalizes the `./tasks/` workflow (one file per change: `YYYY-MM-DD-slug.md`), enforces ADR reading/creation rules, and adds a label so **DeepWiki** can continuously scrape and keep the repository documentation up to date.
This PR is documentation/process-only; it makes no behavioral changes to the library itself.
* Add `copilot-instructions.md` at the repo root (English)
* Define strict **TDD workflow** and **task files** convention:
* `./tasks/` with per-change files named `YYYY-MM-DD-slug.md`.
* Keep **.task/** as local working folder (ignored by Git) for any transient notes.
* Add `.gitignore` entries:
* `/.task/` → not versioned.
* Clarify **ADR policy**:
* Read existing …
> chore: add copilot-instructions.md for the repo

- CHANGELOG.md
- build.sh
`set_test_title` helper is not available in the single file library because it's not being pulled in by the build script. Fix it.
(see above)
> Include test_title.sh in build depenedencies

- CHANGELOG.md
- docs/test-files.md
- src/helpers.sh
- src/runner.sh
- src/state.sh
- tests/acceptance/bashunit_setup_before_script_error_test.sh
- tests/acceptance/bashunit_setup_error_test.sh
- tests/acceptance/bashunit_teardown_after_script_error_test.sh
- tests/acceptance/bashunit_teardown_error_test.sh
- tests/acceptance/fixtures/test_bashunit_when_setup_before_script_errors.sh
- tests/acceptance/fixtures/test_bashunit_when_setup_errors.sh
- tests/acceptance/fixtures/test_bashunit_when_teardown_after_script_errors.sh
- tests/acceptance/fixtures/test_bashunit_when_teardown_errors.sh
- tests/unit/globals_test.sh
- tests/unit/redirect_error_test.sh
- tests/unit/state_test.sh
Closes: https://github.com/TypedDevs/bashunit/issues/489 by @carlfriedrich 
If there would be an error in `set_up_before_script` or  similars, then bashunit crash and does not continue with the tests; also, it does not give any feedback about it but stops working.
You can see in the demo above, that the runner stops without giving any hint why.
- Do not stop when encountering any error on set_up functions, but keep the error on memory and keep the runner running
> Fix setup and teardown functions when errors

- CHANGELOG.md
- src/test_doubles.sh
- tests/unit/test_doubles_test.sh
Closes https://github.com/TypedDevs/bashunit/issues/494 by @mattness
> Fix false negative from assert_have_been_called_with with pipes

- CHANGELOG.md
- src/bashunit.sh
- tests/functional/custom_asserts_test.sh
Closes https://github.com/TypedDevs/bashunit/issues/500
Custom assert output to be consistent with bashunit's built-in assertions.
- Changing `${FUNCNAME[1]}` to `${FUNCNAME[2]}` by @mattness [source](https://github.com/TypedDevs/bashunit/issues/500#issuecomment-3368668111)
> Fix wrong assertion_failed name of test on failure
