TypedDevs/bashunit

src/assert.sh
tests/unit/assert_test.sh

Related to: https://github.com/Chemaclass/bashunit/issues/24

chore: create function assertNotMatches

---

bashunit
src/assert.sh
src/helpers.sh
src/test_runner.sh
tests/unit/helpers_test.sh

- Move `normalizeFunctionName` to `helpers.sh`
- Rename `normalizeFunctionName` to `normalizeTestFunctionName`
- Added tests for `normalizeTestFunctionName`

Refactor normalizeFunctionName

---

CHANGELOG.md
example/README.md

Add real examples on the visual documentation, so people could copy paste them
- add examples to readme on the example folder

docs: add copy paste documentation on how to use our functions

---

LICENSE

- Updated LICENSE to include all main contributors from TypedDevs

Update LICENSE to include all main contributors from TypedDevs

---

tests/unit/assert_test.sh
tests/unit/console_results_test.sh

Change some asserts for other better and add missing test

chore: improve some asserts

---

CHANGELOG.md
src/assert.sh
tests/unit/assert_test.sh

How to assert that we have something on an array
- added `assertArrayContains`
- added `assertArrayNotContains`

add assertArrayContains and assertArrayNotContains

---

.github/workflows/contributors.yml
README.md

Add action to show contributors on the readme.md file

chore: add contributors

---

.github/workflows/contributors.yml

Add action to create contributors and run it also on PR

chore: added contributors to the pr process too

---

docs/index.md

- Improve the docs homepage features section

Improve doc index features

---

src/assert.sh
src/console_results.sh
src/helpers.sh
src/runner.sh
tests/unit/assert_test.sh
tests/unit/console_results_test.sh
tests/unit/helpers_test.sh

Added prefixes to the _core_ function names like _namespaces_ for a better code organization and understanding

Add namespace function names

---

bpkg.json

Related to: https://github.com/bpkg/bpkg.github.io/pull/82 
- Create a `bpkg.json` following https://bpkg.sh/guidelines/

Add bpkg.json

---

docs/assertions.md

Add docs for assertEmpty and assertNotEmpty

---

docs/.vitepress/config.ts
docs/.vitepress/theme/style.css
docs/test-files.md
yarn.lock

I've added a section to the documentation that deals with test files. I'm not really satisfied with the outcome and wouldn't mind getting your feedback, or even feel free to modify this PR.
- Add test files section to docs (closes #108)
- Test file names
- Test function names
- `setUp` function
- `tearDown` function
- `setUpBeforeScript` function
- `tearDownAfterScript` function
- Update VitePress
- Remove footer from docs (closes #110)

Doc test files

---

.editorconfig
docs/.vitepress/config.ts

Enable sitemap.xml generation

---

bashunit
src/runner.sh

The `runner.sh` file contain functions AND the main logic, that should be in the entrypoint file: `./bashunit`
- Move main logic from `runner.sh` file to `./bashunit` entrypoint

Extract main from runner.sh to bashunit

---

docs/.vitepress/config.ts

Clean urls to .vitepress/config.ts, this way URLS will not contain .html
- add: cleanUrls: true, in  .vitepress/config.ts,

Clean URLs

---

docs/.vitepress/config.ts
docs/getting-started.md
docs/mocks.md
docs/test-doubles.md

Add mocks docs

---

docs/assertions.md

- Add docs for the newly file assert functions
- assert_file_exists
- assert_file_not_exists
- assert_is_file_empty
- assert_is_file

Docs for files asserts

---

.github/workflows/deploy-docs.yml

Change branch of deploy-docs workflow to latest so this way we don't show "non released" features in the docs.

Change branch of deploy-docs workflow to latest

---

CHANGELOG.md
docs/test-files.md
src/runner.sh
tests/unit/setup_teardown_test.sh

- Rename set_up/tear_down functions from camelCase to snake_case

Rename set_up/tear_down functions from camelCase to snake_case

---

bashunit
src/assert.sh
src/console_results.sh
src/helpers.sh
src/runner.sh
src/state.sh
src/test_doubles.sh
tests/unit/state_test.sh

Refactor all the state function names to follow the [Google Shell Style Guide](https://google.github.io/styleguide/shellguide.html)
It's an internal refactor so I didn't added it to the CHANGELOG.md

Refactor state functions

---

CHANGELOG.md
bashunit
docs/getting-started.md
docs/test-files.md
src/helpers.sh

Issue: https://github.com/TypedDevs/bashunit/issues/139
- Allow running `./bashunit` over a full directory
- Update docs

Find all test on a directory

---

install.sh

fix: installer default version

---

.github/RELEASE.md

The creation of a new release needs some manual steps. The goal is to have a guide that will allow us to create releases in a unified way by anyone.
- Create a release documentation page

Create RELEASE documentation

---

docs/.vitepress/theme/style.css

Added back the footer links, as we ended up removing the sidebar anchors; they seem like an engaging way to finish reading through the documentation.

Add footer links

---

docs/.vitepress/config.ts

Add last updated to every doc page.

Add last updated

---

docs/.vitepress/config.ts

Added edit links to all pages, allowing our users to fix errors in our documentation extremely simply.

Add edit link

---

docs/installation.md

Small docs fixes

---

CHANGELOG.md
docs/assertions.md
src/assert.sh
tests/unit/assert_test.sh

- Add `assert_less_than`
- Add `assert_less_or_equal_than`
- Add `assert_greater_than`
- Add `assert_greater_or_equal_than`

Asserts less|greater [or equal] than

---

.github/RELEASE.md
CHANGELOG.md
docs/quickstart.md
install.sh
tests/acceptance/install_test.sh

closes #194
@ImanolRP was pairing with me during this pr
- Installer is not longer the builder
- Added acceptance tests to the installer 🎊 
- Little fix quickstart command

Fix and test installer

---

CHANGELOG.md
docs/assertions.md
src/assert.sh
tests/unit/assert_test.sh

Adds the `assert_contains_ignore_case` assertion.

chore: assert_contains_ignore_case

---

CHANGELOG.md
docs/.vitepress/config.ts
docs/command-line.md
docs/configuration.md
docs/env-config.md

- Add a new documentation page for env-vars
https://github.com/TypedDevs/bashunit/assets/5256287/10049843-dffe-4322-9f5c-ef03d64fe4d2

Add docs for env config

---

.github/ISSUE_TEMPLATE/BUG.md
docs/assertions.md
docs/command-line.md
docs/configuration.md
docs/quickstart.md
package.json
yarn.lock

I've changed some definitions and generally improved the documentation, emphasizing the greater/less than asserts and also on the configuration and command line sections.
Closes #214

Docs greater less than

---

docs/command-line.md
docs/configuration.md
docs/quickstart.md
docs/standalone.md

- Add `bash` style on docs' "bash examples"
- improve `docs/standalone.md`

Minor docs style improvements

---

tests/unit/redirect_error_test.sh

Issue: https://github.com/TypedDevs/bashunit/issues/272 by @lanyou0 
This PR is not "solving" the issue itself, but hopefully is creating clarity of how to deal with it.
- Add a test to understand how to deal with a function that is rendering to the error file descriptor (2), and how to write a test for it

Test: redirect file descriptor error

---

build.sh
tests/acceptance/bashunit_upgrade_test.sh

- Enable `test_do_not_update_on_consecutive_calls`
- Run all tests when creating a new build
- Possible to disable this with `--ignore-verify`
- Add spinner when running all tests
https://github.com/user-attachments/assets/65d09863-557f-4171-88ff-068c69bb11e4

Improve build

---

CHANGELOG.md
docs/installation.md

I tried to set up the github actions and found that there is some missing steps in the snippet provided
- Updated docs with three extra steps to bashunit installation

Updated docs with three extra steps to bashunit installation for github actions

---

.github/workflows/tests.yml
CHANGELOG.md
src/console_results.sh
src/runner.sh
src/state.sh
tests/acceptance/bashunit_direct_fn_call_test.sh
tests/unit/assert_snapshot_test.sh
tests/unit/file_test.sh

The output for simple output was not ideal before, because it didnt work for non-succesful tests.
- Improve simple output view

Improve simple output

---

CHANGELOG.md
src/console_results.sh
tests/unit/console_results_test.sh

- Display seconds if total time taken is >=1000 ms

Display seconds on time taken

---

CHANGELOG.md
src/console_results.sh
src/runner.sh
tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_with_wildcard.snapshot
tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_directory.snapshot
tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_simple_output_env.snapshot
tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_simple_output_option.snapshot
tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_argument_overloads_default_path.snapshot
tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_argument_path.snapshot
tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_env_default_path.snapshot
tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_env.snapshot
tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_option.snapshot

- Improved output: adding a space between each test file

Improve the output adding a space between each test file

---

CHANGELOG.md
docs/snapshots.md
src/assert_snapshot.sh
tests/unit/assert_snapshot_test.sh

You might want to assert snapshots with custom text to be ignore, like date or time.
- Support using `::ignore::` as placeholder to ignore in the snapshots

Support placeholder ignore in snapshots

---

CHANGELOG.md
docs/.vitepress/config.ts
docs/project-overview.md

Add project overview to website

---

CHANGELOG.md
src/clock.sh
tests/unit/clock_test.sh

Improve clock performance

---

CHANGELOG.md
src/env.sh
tests/unit/directory_test.sh

- Fixed terminal width detection first tput and fall back stty

Fix terminal width first tput and fall back stty

---

.github/workflows/build.yml
CHANGELOG.md
docs/command-line.md
src/console_header.sh
tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot

- Update the `--help` message and optimize the text
- Add build and verify workflow

Optimize help message

---

CHANGELOG.md
bashunit
docs/command-line.md
docs/configuration.md
src/env.sh
tests/acceptance/bashunit_no_output_test.sh

- Add new option `--no-output`

Add --no-output option

---

CHANGELOG.md
docs/configuration.md
docs/globals.md
src/console_header.sh
src/env.sh
src/globals.sh
src/main.sh
src/parallel.sh
src/runner.sh
src/state.sh
tests/acceptance/snapshots/bashunit_benchmark_test_sh.test_bashunit_functional_benchmark.snapshot
tests/acceptance/snapshots/bashunit_benchmark_test_sh.test_bashunit_runs_benchmark_file.snapshot
tests/unit/globals_test.sh

Replace this text with a short description of your feature/bugfix.
- Add more internal dev log messages and prefix them with [INTERNAL]
- Toggle internal log messages with `BASHUNIT_INTERNAL_LOG=true|false`

Improve dev log internal messages

---

.github/workflows/tests.yml

Related: https://github.com/TypedDevs/bashunit/pull/452#issuecomment-3121788777 @drupol

Remove unnecessary nixos gh workflow

---

CHANGELOG.md
src/helpers.sh
src/runner.sh
tests/acceptance/snapshots/bashunit_exit_code_test_sh.test_bashunit_when_a_test_returns_non_zero.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_simple_output_env.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_simple_output_option.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_env.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_option.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_with_a_test_fail_and_exit_immediately.snapshot
tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_with_multiple_failing_tests.snapshot
tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_env.snapshot
tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_option.snapshot
tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_env.snapshot
tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_option.snapshot
tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_env.snapshot
tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_env_simple_output.snapshot
tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_option.snapshot

- Add line number to failing tests

Add line number to failing tests

---

CHANGELOG.md
src/reports.sh
tests/unit/reports_test.sh

Skip report tracking unless requested to gain some performance

Skip report tracking unless requested
